version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: comp3123_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=comp3123_assignment1
    ports:
      - 27018:27017
    volumes:
      - mongo_data_comp3123_assignment1:/data/db
    networks:
      - comp3123_assignment1_network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0-20
    container_name: comp3123_mongo_express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    ports:
      - 8081:8081
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - comp3123_assignment1_network
    restart: unless-stopped

volumes:
  mongo_data_comp3123_assignment1:
    driver: local

networks:
  comp3123_assignment1_network:
    driver: bridge