version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data_comp3123_assignment1:/data/db
    networks:
      - comp3123_assignment1_network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - comp3123_assignment1_network
    restart: unless-stopped

volumes:
  mongo_data_comp3123_assignment1:

networks:
  comp3123_assignment1_network:
    driver: bridge